### ISSUE TITLE
"scrapy list" gives an error

### ISSUE THREAD

**Issue by cityscrapers-brian** [bonfirefan/city-scrapers-pitt#28]
# scrapy list
Traceback (most recent call last):
  File "/sda9/cityscrapers-sandbox/bin/scrapy", line 10, in <module>
    sys.exit(execute())
  File "/sda9/cityscrapers-sandbox/lib/python3.7/site-packages/scrapy/cmdline.py", line 150, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/sda9/cityscrapers-sandbox/lib/python3.7/site-packages/scrapy/cmdline.py", line 90, in _run_print_help
    func(*a, **kw)
  File "/sda9/cityscrapers-sandbox/lib/python3.7/site-packages/scrapy/cmdline.py", line 157, in _run_command
    cmd.run(args, opts)
  File "/sda9/cityscrapers-sandbox/lib/python3.7/site-packages/city_scrapers_core/commands/list.py", line 8, in run
    print("{0: <6} |  {1}".format(s, getattr(cls, "agency", cls.agency_name)))
AttributeError: type object 'AlleCountySpider' has no attribute 'agency_name'

**Comment by jtotoole** [comment]
This requires a change to the `city-scrapers-core` package, a dependency of this project. I submitted a PR for said change here: https://github.com/City-Bureau/city-scrapers-core/pull/5

That said, all `scrapy list` does is list the spiders in the `city-scrapers-pitt/city_scrapers/spiders/` directory, so if you need this info just look there.

This bug will presumably be resolved in the next version of the `city-scrapers-core` package; since it can't be fixed from within this repo I'd suggest this issue be closed

**Comment by bonfirefan** [comment]
As @jtotoole mentioned, this is indeed fixed with the next `city-scrapers-core` .

**Comment by cityscrapers-brian** [comment]
Do we need to update the city-scrapers-core version in the requirements.txt file as a result of this?
requirements.txt (at least on my computer) says "==0.2.0" of city-scrapers-core.

**Comment by jtotoole** [comment]
yeah, i'm happy to bump it once https://github.com/bonfirefan/city-scrapers-pitt/pull/35 gets merged
