### ISSUE TITLE
Pennsylvania Liquour Board Crashes and Yields No Events

### ISSUE THREAD

**Issue by ben-nathanson** [bonfirefan/city-scrapers-pitt#88]
:thinking:

Checking the WayBack Machine, it doesn't look like the website changed much. Any thoughts on why this happened and what we could change?

```bash
(city-scrapers-pitt) $scrapy crawl pa_liquorboard
2020-01-27 22:31:25 [scrapy.utils.log] INFO: Scrapy 1.8.0 started (bot: city_scrapers)
2020-01-27 22:31:26 [scrapy.utils.log] INFO: Versions: lxml 4.4.2.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.5.2, w3lib 1.21.0, Twisted 19.10.0, Python 3.7.5 (default, Nov 13 2019, 13:25:19) - [Clang 11.0.0 (clang-1100.0.33.12)], pyOpenSSL 19.1.0 (OpenSSL 1.1.1d  10 Sep 2019), cryptography 2.8, Platform Darwin-19.2.0-x86_64-i386-64bit
2020-01-27 22:31:26 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'city_scrapers', 'CLOSESPIDER_ERRORCOUNT': 5, 'COMMANDS_MODULE': 'city_scrapers_core.commands', 'NEWSPIDER_MODULE': 'city_scrapers.spiders', 'SPIDER_MODULES': ['city_scrapers.spiders'], 'USER_AGENT': 'City Scrapers [development mode]. Learn more and say hello at https://www.citybureau.org/city-scrapers/'}
2020-01-27 22:31:26 [scrapy.extensions.telnet] INFO: Telnet Password: nice try
2020-01-27 22:31:26 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats']
2020-01-27 22:31:26 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2020-01-27 22:31:26 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2020-01-27 22:31:26 [scrapy.middleware] INFO: Enabled item pipelines:
['city_scrapers_core.pipelines.DefaultValuesPipeline',
 'city_scrapers_core.pipelines.MeetingPipeline']
2020-01-27 22:31:26 [scrapy.core.engine] INFO: Spider opened
2020-01-27 22:31:26 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2020-01-27 22:31:26 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2020-01-27 22:31:27 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.lcb.pa.gov/About-Us/Board/Pages/Public-Meetings.aspx> (referer: None)
2020-01-27 22:31:27 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.lcb.pa.gov/About-Us/Board/Pages/Public-Meetings.aspx> (referer: None)
Traceback (most recent call last):
  File "/Users/ben/.local/share/virtualenvs/city-scrapers-pitt-YjN_7ZsS/lib/python3.7/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/Users/ben/.local/share/virtualenvs/city-scrapers-pitt-YjN_7ZsS/lib/python3.7/site-packages/scrapy/core/spidermw.py", line 84, in evaluate_iterable
    for r in iterable:
  File "/Users/ben/.local/share/virtualenvs/city-scrapers-pitt-YjN_7ZsS/lib/python3.7/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/Users/ben/.local/share/virtualenvs/city-scrapers-pitt-YjN_7ZsS/lib/python3.7/site-packages/scrapy/core/spidermw.py", line 84, in evaluate_iterable
    for r in iterable:
  File "/Users/ben/.local/share/virtualenvs/city-scrapers-pitt-YjN_7ZsS/lib/python3.7/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/Users/ben/.local/share/virtualenvs/city-scrapers-pitt-YjN_7ZsS/lib/python3.7/site-packages/scrapy/core/spidermw.py", line 84, in evaluate_iterable
    for r in iterable:
  File "/Users/ben/.local/share/virtualenvs/city-scrapers-pitt-YjN_7ZsS/lib/python3.7/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/Users/ben/.local/share/virtualenvs/city-scrapers-pitt-YjN_7ZsS/lib/python3.7/site-packages/scrapy/core/spidermw.py", line 84, in evaluate_iterable
    for r in iterable:
  File "/Users/ben/.local/share/virtualenvs/city-scrapers-pitt-YjN_7ZsS/lib/python3.7/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/Users/ben/Desktop/throw/city-scrapers-pitt/city_scrapers/spiders/pa_liquorboard.py", line 38, in parse
    start=self._parse_start(item),
  File "/Users/ben/Desktop/throw/city-scrapers-pitt/city_scrapers/spiders/pa_liquorboard.py", line 66, in _parse_start
    date_object = datetime.date(datetime.strptime(" ".join(item.split()[-3:]), '%B %d, %Y'))
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '-' does not match format '%B %d, %Y'
2020-01-27 22:31:27 [scrapy.core.engine] INFO: Closing spider (finished)
2020-01-27 22:31:27 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 323,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 41906,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'elapsed_time_seconds': 1.45097,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2020, 1, 28, 3, 31, 27, 573543),
 'log_count/DEBUG': 1,
 'log_count/ERROR': 1,
 'log_count/INFO': 10,
 'memusage/max': 59457536,
 'memusage/startup': 59457536,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'spider_exceptions/ValueError': 1,
 'start_time': datetime.datetime(2020, 1, 28, 3, 31, 26, 122573)}
2020-01-27 22:31:27 [scrapy.core.engine] INFO: Spider closed (finished)
```

**Comment by ben-nathanson** [comment]
Resolved by #91
